### ISSUE TITLE
Tutorial files

### ISSUE THREAD

**Issue by JBreunig** [aertslab/ScoMAP#1]
Our group is very interested in adapting ScoMAP to our development project.  Might you be able to make the files used in the tutorial available or did we miss them somewhere?
Thanks in advance!
Josh

**Comment by cbravo93** [comment]
Hi @JBreunig !

Thanks for your interest in ScoMAP! Some of the files were missing due to its size (only the output folder is the repository), I have added a [link](https://drive.google.com/drive/folders/1ESa4MB0WXzpMgsk1mMAVWWE21vAjpINt?usp=sharing) to all the data used in the tutorial to the README file. The code to generate the objects in 'Omics' is available [here](https://github.com/aertslab/Bravo_et_al_EyeAntennalDisc), on the Figure 1 and Figure 2 vignettes (with Seurat and cisTopic, respectively).

Let me know if you have further questions!

C

**Comment by JBreunig** [comment]
Will do...thank you!
